### ISSUE TITLE
作者大大，能帮我看下吗，我想问下个人部署存储设置你们是怎么配置的，我这边用又拍云可以存到图床存储桶中，但是上传成功后路径不显示存储桶的路径。

### ISSUE THREAD

**Issue by YunhaiHu** [Robert-Stackflow/Moment#5]
下面是配置截图，新增图片存储桶的路径显示不出来。
<img src="https://upyun.yunhai.club/blog/001.png" width="45%">

<img src="https://upyun.yunhai.club/blog/002.png" width="45%">

**Comment by Robert-Stackflow** [comment]
又拍云中能够看到上传后的图片文件吗，正确的路径(也就是你能访问到图片的路径）应该是什么？我看你路径里有个空格，是这个问题吗？

**Comment by YunhaiHu** [comment]
我应该是那里写错了，改了下可以了，谢谢。这个相册感觉很好的😉

<img src="https://upyun.yunhai.club/blog/041.png"  width=30%>

**Comment by YunhaiHu** [comment]
还对比了下路径，那个空格我后面发现了，确实是多了👍。
